//StAuth10244: I Adam Calleja, 000862779 certify that this material is my original work. No other person's work has been used without due acknowledgement. I have not made my work available to anyone else.
const bases = [
    {
        "baseid": 0,
        "basename": "Garrison Petawawa",
        "basetype": "Army",
        "division": "4th Canadian Divison",
        "address": "101 Menin Road",
        "postal": "K8H 2X3",
        "city": "Petawawa",
        "province": "ON",
        "latitude": 45.9117162,
        "longitude": -77.2933546,
        "baseimg": "images/petawawa.jpg"
    }, 
    {
        "baseid": 1,
        "basename": "CFB Kingston",
        "basetype": "Army",
        "division": "4th Canadian Divison",
        "address": "26 Somme Ave",
        "postal": "K7K 7B4",
        "city": "Kingston",
        "province": "ON",
        "latitude": 44.2438099,
        "longitude": -76.4427962,
        "baseimg": "images/kingston.png"
    }, 
    {
        "baseid": 2,
        "basename": "CFB Montreal",
        "basetype": "Army",
        "division": "2nd Canadian Divison",
        "address": "6769 Notre-Dame Street",
        "postal": "H1N 2E9",
        "city": "Montreal",
        "province": "QC",
        "latitude": 45.5721829,
        "longitude": -73.5206641,
        "baseimg": "images/montreal.jpg"
    },
    {
        "baseid": 3,
        "basename": "CFB Valcartier",
        "basetype": "Army",
        "division": "2nd Canadian Divison",
        "address": "Rue Chassé",
        "postal": "G0A 4N0",
        "city": "La Jacques-Cartier",
        "province": "QC",
        "latitude": 46.886234,
        "longitude": -71.4917649,
        "baseimg": "images/valcartier.jpeg"
    },
    {
        "baseid": 4,
        "basename": "CFB Gagetown",
        "basetype": "Army",
        "division": "5th Canadian Divison",
        "address": "100 Broad Road",
        "postal": "E2V 4J5",
        "city": "Oromocto",
        "province": "NB",
        "latitude": 45.8408074,
        "longitude": -66.4712308,
        "baseimg": "images/gagetown.jpg"
    },
    {
        "baseid": 5,
        "basename": "CFB Halifax",
        "basetype": "Navy",
        "division": "Maritime Forces Atlantic",
        "address": "5470 Gangway Rd",
        "postal": "NS B3K",
        "city": "Halifax",
        "province": "NS",
        "latitude": 44.6600466,
        "longitude": -63.596915,
        "baseimg": "images/halifax.jpg"
    },
    {
        "baseid": 6,
        "basename": "Garrison St. John's",
        "basetype": "Navy",
        "division": "Maritime Forces Atlantic",
        "address": "115 The Blvd",
        "postal": "A1A 1K3",
        "city": "St. John's",
        "province": "NL",
        "latitude": 47.5825684,
        "longitude": -52.6975399,
        "baseimg": "images/stjohns.jpg"
    },
    {
        "baseid": 7,
        "basename": "CFB Trenton",
        "basetype": "AirForce",
        "division": "Royal Canadian Air Force",
        "address": "6 Northstar Dr",
        "postal": "K8V 5P8",
        "city": "Trenton",
        "province": "ON",
        "latitude": 44.1162969,
        "longitude": -77.5379157,
        "baseimg": "images/trenton.jpg"
    },
    {
        "baseid": 8,
        "basename": "CFB Borden",
        "basetype": "AirForce",
        "division": "Royal Canadian Air Force",
        "address": "620 Ortona Rd",
        "postal": "L0M 1C0",
        "city": "Borden",
        "province": "ON",
        "latitude": 44.2628699,
        "longitude": -79.9036985,
        "baseimg": "images/borden.jpg"
    },
    {
        "baseid": 9,
        "basename": "CFB Greenwood",
        "basetype": "AirForce",
        "division": "Royal Canadian Air Force",
        "address": "124 Pathfinder Dr",
        "postal": "B0P 1N0",
        "city": "Greenwood",
        "province": "NS",
        "latitude": 44.9779364,
        "longitude": -64.9284998,
        "baseimg": "images/greenwood.jpg"
    },
    {
        "baseid": 10,
        "basename": "CFB Gander",
        "basetype": "AirForce",
        "division": "Royal Canadian Air Force",
        "address": "Washington Ave",
        "postal": "A1V 2V6",
        "city": "Gander",
        "province": "NL",
        "latitude": 48.9444326,
        "longitude": -54.5839316,
        "baseimg": "images/gander.jpg"
    },
]